# This is a basic workflow to help you get started with Actions

name: Deploy to Cloud Run

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    
    - name: Store GITHUB_TOKEN on disk
      run: echo ${{ secrets.GITHUB_TOKEN }} > $GITHUB_WORKSPACE/examples/gh.token

    # Runs a single command using the runners shell
    - name: Run deploy script
      run: GITHUB_TOKEN_PATH=$GITHUB_WORKSPACE/examples/gh.token $GITHUB_WORKSPACE/examples/bazel-deploy.sh
